### PR TITLE
test: add check for proxy scheme

### PR DESCRIPTION
**Pull request by richm**
add a test for the proxy scheme, and use a non default value
to ensure it is being used.

Signed-off-by: Rich Megginson <rmeggins@redhat.com>

### CODE REVIEW

**Comment by richm** [comment]
[citest]

**Comment by richm** [comment]
hopefully we'll get ci test results. I've tested this locally (tox -e qemu... tests/tests_proxy.yml) and it works with `https`

**Comment by richm** [comment]
[citest]

**Comment by ptoscano** [comment]
[citest pending]

**Review by ptoscano — APPROVED** [review]
LGTM, thanks!

I'm kinda surprised that the default configuration of squid enabled the https proxying without any additional bits (i.e. custom CA certificate, etc). But well, if it works, why not... :)

(waiting for CI to finish before merging)

**Comment by ptoscano** [comment]
[citest bad]

**Comment by richm** [comment]
> LGTM, thanks!
> 
> I'm kinda surprised that the default configuration of squid enabled the https proxying without any additional bits (i.e. custom CA certificate, etc). But well, if it works, why not... :)

Might be a bug - not sure why it is working.

> 
> (waiting for CI to finish before merging)

**Comment by richm** [comment]
> > This looks related to ansible-core 2.15
> 
> I have the feeling it might be [ansible-collections/community.general#6401](https://github.com/ansible-collections/community.general/pull/6401)

yes, looks that way

**Comment by ptoscano** [comment]
Finally this can be rebased, and it will work fine :) (_famous last words_)

**Comment by richm** [comment]
[citest]

**Review by ptoscano — APPROVED** [review]
LGTM, thanks!

Will wait for green CI before merging.

**Comment by richm** [comment]
CentOS-Stream-8/ansible-2.9 had an unrelated problem - merging

**Pull request merged**
