### PR TITLE
docs(changelog): version 1.6.1 [citest skip]

### PR DESCRIPTION
**Pull request by spetrosi**
Update changelog and .README.html for version 1.6.1

Signed-off-by: Sergei Petrosian <spetrosi@redhat.com>

### CODE REVIEW

**Comment by ptoscano** [comment]
@spetrosi not sure whether you noticed these failures in the ansible test:
```
ERROR: docs/CHANGELOG_rhc.md:24:128: use ASCII quotes `'` and `"` instead of Unicode quotes
ERROR: roles/rhc/CHANGELOG.md:24:128: use ASCII quotes `'` and `"` instead of Unicode quotes
```

**Comment by richm** [comment]
> @spetrosi not sure whether you noticed these failures in the ansible test:
> 
> ```
> ERROR: docs/CHANGELOG_rhc.md:24:128: use ASCII quotes `'` and `"` instead of Unicode quotes
> ERROR: roles/rhc/CHANGELOG.md:24:128: use ASCII quotes `'` and `"` instead of Unicode quotes
> ```

Yes - that's bad - needs to be fixed - not sure how `Result:
  Consistently with a similar condition of the display_name parameter, an empty string ansible_host is treated as undefined. It’s the same behavior as with a null value.` got added with the `’` unicode quote mark

**Comment by ptoscano** [comment]
It's the text of the PR #169. I just edited it to switch the apostophe to an ASCII character, so would you please try to run the release automation again?

**Comment by spetrosi** [comment]
ansible-test is more and more strict. I've modified changelog entry.

**Review by ptoscano — APPROVED** [review]

**Pull request merged**
