### PR TITLE
add weekly-ci action

### PR DESCRIPTION
**Pull request by ukulekek**
Signed-off-by: Evgeny Fedin <efedin@redhat.com>

### CODE REVIEW

**Comment by ukulekek** [comment]
This action will trigger the CI system to test the role every weekend. It will ensure the role didn't break because of dependencies and other factors while being inactively developed. See https://url.corp.redhat.com/1ab3ab1 for more details

**Comment by ptoscano** [comment]
can you please rebase this on current `main`? it should work fine now

**Comment by ukulekek** [comment]
Thanks, @ptoscano. I need to rewrite it a bit before merging. See RHELPLAN-132773

**Comment by ukulekek** [comment]
The PR is updated to the latest version @richm

**Comment by ptoscano** [comment]
Thanks! Can you please rebase it on top of `main`? It is slightly behind it.

I see lot of code that is copied among the same actions in other LSR repos; while I don't want to block on this, I think maybe it would be better to create a new github action, so it can be used e.g. as:
```yaml
      - uses: linux-system-roles/periodic-check@v1
        with:
          branch-name: "weekly-ci"  [ maybe optional ]
          commit-message: "This PR ..."  [ maybe optional ]
          body-message: "This PR ..."  [ maybe optional ]
          comment: "[citest]"  [ maybe optional ]
```

**Comment by ukulekek** [comment]
@ptoscano I rebased it. That is a great idea. We can uniform it in future.

**Pull request merged**
